title: Sebastian Gabriel Ponce de Leon # your name (or website title) here
logo: "/images/Foto.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Cordoba, Argentina
  <br><br>
  Objetivo: Desarrollarme y adquirir experiencia en el campo de la Ciencia de datos, fundamentalmente en modelado y aprendizaje automatico  
  <br><br>
  Tengo experiencia en Analisis y modelizacion predictiva
  <br><br>
  <a href="https://www.linkedin.com/in/proserix/">Entra a mi perfil de LinkedIn</a> 
  <br><br>
  <a href="/pdf/CV_Seba_actual.pdf">Mira mi Curriculum Vitae (CV) </a> 
  
theme: jekyll-theme-minimal
